kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t point .

- name: run
  image: point
  pull: if-not-exists
  commands:
  - export CIRCLE_SHA1=$(git rev-parse HEAD)
  - rove point.asd
  - coveralls report/
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
    COVERAGE: 1
    COVERAGE_EXCLUDE: '/drone/src/test'
    CIRCLECI: 1
    CL_SOURCE_REGISTRY: '/drone/src'

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
